ibs/maluspunten/urls.py
from django.urls import path

from ibs.maluspunten import views

app_name = 'maluspunten'

urlpatterns = [
  path('', views.index, name='index'),
  path('gelukt/', views.success, name='success'),
  path('overzicht/', views.overview, name='overview')
]

ibs/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # django
    path('admin/', admin.site.urls),

    # dependencies
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('knox/', include('knox.urls')),

    # apps
    path('financial/', include('ibs.financial.urls')),
    path('activity/', include('ibs.activity.urls')),
    path('chugs/', include('ibs.chugs.urls')),
    path('user/', include('ibs.users.urls')),
    path('maluspunten/', include('ibs.maluspunten.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ibs/maluspunten/models.py
from django.db import models

from ibs.tools.mixins import BaseMixin
from ibs.users.models import User

class Maluspunt(BaseMixin):
  user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='maluspunten_user')
  added_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='maluspunten_added_by'	)
  reason = models.CharField(max_length=1024)
  amount = models.IntegerField()
  
  def __str__(self):
    return f'{self.user.first_name} - {self.reason} - {self.amount}'
  
  class Meta:
    verbose_name = 'Maluspunt'
    verbose_name_plural = 'Maluspunten'

ibs/maluspunten/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from ibs.users.models import User
from ibs.maluspunten.models import Maluspunt
from ibs.maluspunten.form import MaluspuntForm

def index(request):
  
  if request.method == 'POST':
    form = MaluspuntForm(request.POST)
    
    if form.is_valid():

      feut = get_object_or_404(User, pk=form.cleaned_data['user'])
      added_by = get_object_or_404(User, pk=form.cleaned_data['added_by'])
      
      Maluspunt.objects.create(
        user=feut,
        added_by=added_by,
        amount=form.cleaned_data['amount'],
        reason=form.cleaned_data['reason']
      )
      
      return HttpResponseRedirect('/maluspunten/gelukt/')

  else:
    form = MaluspuntForm(initial={'added_by': request.user.id})
      
    return render(request, 'index.html', {
      'form': form,
      'user': request.user,
    })
    
    
def success(request):
  return render(request, 'success.html')


def overview(request):
  maluspunten = Maluspunt.objects.all()
  
  return render(request, 'overview.html', {
    'maluspunten': maluspunten
  })

ibs/maluspunten/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Maluspunten</title>

  <style>
    body {
      font-family: sans-serif;
    }

    form {
      display: flex;
      flex-direction: column;
      width: 100%;
    }

    form > div {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }

    form > label {
      margin-top: 1rem;
    }

    form > input {
      margin-top: 0.5rem;
    }

    form > button {
      margin-top: 1rem;
    }
  </style>
</head>

<body>
  <h1>
    Hoi {{ user.first_name }}
  </h1>
  <p>
    Voeg hier een maluspunt toe
  </p>
  <form method="post">
    {% csrf_token %}
    {{ field.errors }}
    {{ form }}

    <button type="submit">Toevoegen</button>
  </form>

  <br>

  <a href="{% url 'maluspunten:overview' %}">Overzicht</a>
  
</body>
</html>

ibs/maluspunten/templates/overview.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Maluspunten overzicht</title>

  <style>
    body {
      font-family: sans-serif;
    }

    table {
      margin-top: 1rem;
      border-collapse: collapse;
    }

    table, th, td {
      border: 1px solid black;
    }

    th, td {
      padding: 0.5rem;
    }
  </style>
</head>
<body>
  <h1>
    Maluspunten
  </h1>

  <a href="{% url 'maluspunten:index' %}">Nieuwe maluspunt</a>

  <table>
    <thead>
      <tr>
        <td>ID</td>
        <td>Feut</td>
        <td>Reden</td>
        <td>Aantal</td>
        <td>Toegevoegd door</td>
        <td>Op</td>
      </tr>
    </thead>

    <tbody>
      {% for maluspunt in maluspunten %}
        <tr>
          <td>{{ maluspunt.id }}</td>
          <td>{{ maluspunt.user.first_name }}</td>
          <td>{{ maluspunt.reason }}</td>
          <td>{{ maluspunt.amount }}</td>
          <td>{{ maluspunt.added_by.first_name }}</td>
          <td>{{ maluspunt.created_at|date:'D. d-m' }}</td>
        </tr>
      {% endfor %}
    </tbody>

  </table>
</body>
</html>

ibs/maluspunten/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Maluspunten</title>

  <style>
    body {
      font-family: sans-serif;
    }

    form {
      display: flex;
      flex-direction: column;
      width: 50%;
    }

    form > div {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }

    form > div > label {
      width: 50%;
    }

    form > div > select {
      width: 50%;
    }

    form > label {
      margin-top: 1rem;
    }

    form > input {
      margin-top: 0.5rem;
    }

    form > button {
      margin-top: 1rem;
    }
  </style>
</head>

<body>
  <h1>
    Lekker man
  </h1>
  
  <a href="{% url 'maluspunten:index' %}">Terug</a>
</body>
</html>